name = 'hugo-blog'
compatibility_date = '2025-07-31'

[vars]
CF_PAGES_URL = 'https://hugo-blog.1252409767.workers.dev'

[build]
command = 'chmod a+x build.sh && ./build.sh'

[assets]
directory = './public'
not_found_handling = '404-page'